

Authorization: PASTE YOUR OAUTH TOKEN HERE
Client-Id: PASTE YOUR CLIENT ID HERE
current-border-size: 100
twitch-update-delay-ticks: 200
streamer_names:
  - <YOUR STREAMERS HERE (OR USE /ADDSTREAMER)>